alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
functions:
- github:
    branch: main
    repo: RatchanonMo/test-workflow
  name: test-workflow2
  source_dir: /
ingress:
  rules:
  - component:
      name: test-workflow
    match:
      path:
        prefix: /
  - component:
      name: test-workflow2
    match:
      path:
        prefix: /test-workflow2
name: monkfish-app
region: sgp
services:
- environment_slug: node-js
  github:
    branch: main
    repo: RatchanonMo/test-workflow
  http_port: 8080
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: test-workflow
  source_dir: /
